FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache libc6-compat python3 make g++

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
ARG NEXT_PUBLIC_IMAGE_STORAGE_MODE
ARG NEXT_PUBLIC_CLIENT_DIRECT_LINK_PRIORITY
ARG CLIENT_DIRECT_LINK_PRIORITY
ARG BETTER_AUTH_SECRET
ARG VERCEL
ARG NEXT_PUBLIC_VERCEL_ENV
ARG UMAMI_SCRIPT_URL
ARG UMAMI_WEBSITE_ID
ENV NEXT_PUBLIC_IMAGE_STORAGE_MODE=${NEXT_PUBLIC_IMAGE_STORAGE_MODE}
ENV NEXT_PUBLIC_CLIENT_DIRECT_LINK_PRIORITY=${NEXT_PUBLIC_CLIENT_DIRECT_LINK_PRIORITY}
ENV CLIENT_DIRECT_LINK_PRIORITY=${CLIENT_DIRECT_LINK_PRIORITY}
ENV VERCEL=${VERCEL}
ENV NEXT_PUBLIC_VERCEL_ENV=${NEXT_PUBLIC_VERCEL_ENV}
ENV UMAMI_SCRIPT_URL=${UMAMI_SCRIPT_URL}
ENV UMAMI_WEBSITE_ID=${UMAMI_WEBSITE_ID}
RUN npm run build

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs && \
    mkdir -p /tmp/gpt-image-playground && \
    chown -R nextjs:nodejs /app /tmp/gpt-image-playground

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
ENV NODE_ENV=production

CMD ["npm", "start"]
