import { createShowcaseTopicAdmin, publishShowcaseTopicAdmin } from './admin';
import {
    ShowcaseAssetInUseError,
    createShowcaseManagedAsset,
    deleteShowcaseManagedAsset,
    getShowcaseManagedAsset,
    getShowcaseManagedAssetFilePath,
    isShowcaseManagedAssetPublic,
    selectReferencedShowcaseTopicDraftAssets
} from './media';
import type { ShowcaseAdminActor, ShowcaseTopicDraft } from './types';
import { DEFAULT_SHOWCASE_CATALOG } from '@/lib/default-showcases';
import { getServerDatabaseReady, getSqliteClient } from '@/lib/server/db';
import { authUsers } from '@/lib/server/schema';
import { NextRequest } from 'next/server';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import { afterAll, afterEach, beforeAll, describe, expect, it } from 'vitest';

const databasePath = path.join(os.tmpdir(), 'gpt-image-playground-showcase-media.test.sqlite');
const mediaDirectory = path.join(os.tmpdir(), 'gpt-image-playground-showcase-media-files');

process.env.ADMIN_DATABASE_PATH = databasePath;
process.env.SHOWCASE_MEDIA_DIR = mediaDirectory;

function actor(): ShowcaseAdminActor {
    return {
        userId: 'showcase-media-admin',
        email: 'showcase-media@example.com',
        role: 'admin',
        request: new NextRequest('https://app.example/api/admin/showcase-assets', {
            headers: { 'user-agent': 'vitest', 'x-forwarded-for': '203.0.113.15' }
        })
    };
}

function draftWithCover(asset: Awaited<ReturnType<typeof createShowcaseManagedAsset>>): ShowcaseTopicDraft {
    const topic = DEFAULT_SHOWCASE_CATALOG.topics[0]!;
    const caseIds = new Set(topic.caseIds);
    const cases = DEFAULT_SHOWCASE_CATALOG.cases.filter((showcaseCase) => caseIds.has(showcaseCase.id));
    const assetIds = new Set<string>([topic.coverAssetId]);
    for (const showcaseCase of cases) {
        assetIds.add(showcaseCase.coverAssetId);
        showcaseCase.inputAssetIds.forEach((id) => assetIds.add(id));
        showcaseCase.outputAssetIds.forEach((id) => assetIds.add(id));
    }
    return {
        topic: { ...topic, coverAssetId: asset.id },
        cases,
        assets: [
            ...DEFAULT_SHOWCASE_CATALOG.assets.filter((candidate) => assetIds.has(candidate.id)),
            asset.catalogAsset
        ]
    };
}

function withDraftIdentity(draft: ShowcaseTopicDraft, suffix: string): ShowcaseTopicDraft {
    const topicId = `${draft.topic.id}-${suffix}`;
    return {
        ...draft,
        topic: { ...draft.topic, id: topicId, slug: `${draft.topic.slug}-${suffix}` },
        cases: draft.cases.map((showcaseCase) => ({ ...showcaseCase, topicId }))
    };
}

async function resetState(): Promise<void> {
    await getServerDatabaseReady();
    getSqliteClient().exec(`
        DELETE FROM "showcase_publication_assets";
        DELETE FROM "showcase_publications";
        DELETE FROM "showcase_topics";
        DELETE FROM "showcase_assets";
        DELETE FROM "audit_logs";
        DELETE FROM "user" WHERE "id" = 'showcase-media-admin';
    `);
    fs.rmSync(mediaDirectory, { recursive: true, force: true });
    const db = await getServerDatabaseReady();
    await db.insert(authUsers).values({
        id: 'showcase-media-admin',
        name: 'Showcase Media Admin',
        email: 'showcase-media@example.com',
        role: 'admin',
        status: 'active'
    });
}

async function jpegFile(): Promise<File> {
    const buffer = await sharp({
        create: { width: 40, height: 20, channels: 3, background: '#9a3412' }
    })
        .jpeg()
        .withMetadata({ orientation: 6 })
        .toBuffer();
    return new File([new Uint8Array(buffer)], 'licensed-source.jpg', { type: 'image/jpeg' });
}

async function uploadAsset() {
    return createShowcaseManagedAsset(
        {
            file: await jpegFile(),
            sourceLabel: 'Synthetic fixture generated by the automated test suite',
            licenseNote: 'Project-owned test fixture; permitted for repository tests',
            altZhCN: '用于专题媒体测试的棕色矩形',
            altEnUS: 'Brown rectangle used for showcase media tests'
        },
        actor()
    );
}

beforeAll(async () => {
    fs.rmSync(databasePath, { force: true });
    fs.rmSync(`${databasePath}-wal`, { force: true });
    fs.rmSync(`${databasePath}-shm`, { force: true });
    await resetState();
});

afterEach(resetState);

afterAll(() => {
    fs.rmSync(mediaDirectory, { recursive: true, force: true });
    fs.rmSync(databasePath, { force: true });
    fs.rmSync(`${databasePath}-wal`, { force: true });
    fs.rmSync(`${databasePath}-shm`, { force: true });
});

describe('showcase managed media', () => {
    it('decodes, rotates, strips metadata, re-encodes, and creates a thumbnail', async () => {
        const asset = await uploadAsset();
        const row = await getShowcaseManagedAsset(asset.id);

        expect(asset.id).toMatch(/^media_[a-f0-9]{32}$/u);
        expect(asset.mimeType).toBe('image/webp');
        expect(asset.width).toBe(20);
        expect(asset.height).toBe(40);
        expect(asset.catalogAsset).toMatchObject({
            managedAssetId: asset.id,
            url: `/api/showcase-media/${asset.id}`,
            thumbnailUrl: `/api/showcase-media/${asset.id}?variant=thumbnail`
        });
        expect(row).not.toBeNull();

        const displayMetadata = await sharp(getShowcaseManagedAssetFilePath(row!, false)).metadata();
        const thumbnailMetadata = await sharp(getShowcaseManagedAssetFilePath(row!, true)).metadata();
        expect(displayMetadata).toMatchObject({ format: 'webp', width: 20, height: 40 });
        expect(displayMetadata.exif).toBeUndefined();
        expect(displayMetadata.orientation).toBeUndefined();
        expect(thumbnailMetadata).toMatchObject({ format: 'webp', width: 20, height: 40 });
    });

    it('rejects declared MIME and decoded format mismatches', async () => {
        const png = await sharp({
            create: { width: 8, height: 8, channels: 3, background: '#0f766e' }
        })
            .png()
            .toBuffer();
        const disguised = new File([new Uint8Array(png)], 'disguised.jpg', { type: 'image/jpeg' });

        await expect(
            createShowcaseManagedAsset(
                {
                    file: disguised,
                    sourceLabel: 'Synthetic test fixture',
                    licenseNote: 'Project-owned test fixture',
                    altZhCN: '伪造格式测试图',
                    altEnUS: 'Disguised format test image'
                },
                actor()
            )
        ).rejects.toThrow('真实格式');
    });

    it('protects draft and publication references while allowing unreferenced cleanup', async () => {
        const referencedAsset = await uploadAsset();
        const draft = draftWithCover(referencedAsset);
        await createShowcaseTopicAdmin({ draft }, actor());

        await expect(deleteShowcaseManagedAsset(referencedAsset.id, actor())).rejects.toBeInstanceOf(
            ShowcaseAssetInUseError
        );
        expect(await isShowcaseManagedAssetPublic(referencedAsset.id)).toBe(false);

        await publishShowcaseTopicAdmin(draft.topic.id, actor());
        expect(await isShowcaseManagedAssetPublic(referencedAsset.id)).toBe(true);
        expect(
            getSqliteClient()
                .prepare('SELECT COUNT(*) AS count FROM "showcase_publication_assets" WHERE "assetId" = ?;')
                .get(referencedAsset.id)
        ).toMatchObject({ count: 1 });

        const unreferencedAsset = await uploadAsset();
        expect(await deleteShowcaseManagedAsset(unreferencedAsset.id, actor())).toBe(true);
        expect(await getShowcaseManagedAsset(unreferencedAsset.id)).toBeNull();
    });

    it('rejects a draft atomically when a referenced managed record is missing', async () => {
        const asset = await uploadAsset();
        const draft = withDraftIdentity(draftWithCover(asset), 'missing-record');
        getSqliteClient().prepare('DELETE FROM "showcase_assets" WHERE "id" = ?;').run(asset.id);

        await expect(createShowcaseTopicAdmin({ draft }, actor())).rejects.toThrow('托管媒体不存在');
        expect(
            getSqliteClient().prepare('SELECT 1 FROM "showcase_topics" WHERE "id" = ?;').get(draft.topic.id)
        ).toBeUndefined();
    });

    it('publishes only referenced managed assets and rejects missing or corrupted media files', async () => {
        const referencedAsset = await uploadAsset();
        const unusedAsset = await uploadAsset();
        const draft = {
            ...draftWithCover(referencedAsset),
            assets: [...draftWithCover(referencedAsset).assets, unusedAsset.catalogAsset]
        };

        expect(
            selectReferencedShowcaseTopicDraftAssets(draft).assets.some((asset) => asset.id === unusedAsset.id)
        ).toBe(false);
        await createShowcaseTopicAdmin({ draft }, actor());
        const publication = await publishShowcaseTopicAdmin(draft.topic.id, actor());
        expect(
            getSqliteClient()
                .prepare('SELECT "assetId" FROM "showcase_publication_assets" WHERE "publicationId" = ?;')
                .all(publication!.id)
        ).toEqual([{ assetId: referencedAsset.id }]);

        const brokenAsset = await uploadAsset();
        const brokenDraft = withDraftIdentity(draftWithCover(brokenAsset), 'missing-file');
        await createShowcaseTopicAdmin({ draft: brokenDraft }, actor());
        const brokenRow = await getShowcaseManagedAsset(brokenAsset.id);
        fs.rmSync(getShowcaseManagedAssetFilePath(brokenRow!, true));
        await expect(publishShowcaseTopicAdmin(brokenDraft.topic.id, actor())).rejects.toThrow('文件不存在');

        const corruptedAsset = await uploadAsset();
        const corruptedDraft = withDraftIdentity(draftWithCover(corruptedAsset), 'corrupted-file');
        await createShowcaseTopicAdmin({ draft: corruptedDraft }, actor());
        const corruptedRow = await getShowcaseManagedAsset(corruptedAsset.id);
        fs.writeFileSync(getShowcaseManagedAssetFilePath(corruptedRow!, false), Buffer.from('corrupted'));
        await expect(publishShowcaseTopicAdmin(corruptedDraft.topic.id, actor())).rejects.toThrow(
            /大小|checksum|解码/u
        );
    });
});
